var nodemailer = require("nodemailer");

var transport = nodemailer.createTransport({
  host: "smtp.1and1.com",
  port: 465,
  auth: {
    user: "zss@narola.email", //example of generated by Mailtrap
    pass: "m(5J?<,<;8%.K4e" //example of generated by Mailtrap
  }
});

var mailOptions = {
  from: "zss@narola.email",
  to: "mkt@narola.email",
  subject: "Test Nodemailer with Mailtrap",

  html: "<h1>Attachments</h1>"
  
};

transport.sendMail(mailOptions, (error, info) => {
  if (error) {
    return console.log(error);
  }
  console.log("Email sent: " + info.response);
});
